version: "2.4"

x-log: &default-log
  options:
    max-size: "10m"
    max-file: "3"

services:
 pg:
    image: postgres:11-alpine
    mem_limit: 2g
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   # - "/volume2/docker_deploy/storage/postgres/data:/var/lib/postgresql/data"
    #   - "./pgdata:/var/lib/postgresql/data"
    logging:
      <<: *default-log
    command: ["-c", "max_connections=300"]